### ISSUE TITLE
Unable to yank / copy in neovim

### ISSUE THREAD

**Issue by tagptroll1** [pop-os/cosmic-term#315]
Tested with 
* neovim v0.11.0-dev-621+g172cc23d8
* latest stable v0.10.1 
 
There is no way for me to extract text from neovim to the clipboard. 
I've tried the `+` and `*` registry, setting these as defaults in my config, 
ctrl + shift +C 
and right click copy the highlighted text.

```
# apt list --installed | grep cosmic-term  
cosmic-term/noble,now 0.1.0~1723901703~24.04~8c55fef amd64 
```
This is making the terminal unusable as a daily driver, any assistance would be greatly appreciated!

**Comment by MoSal** [comment]
* Do you have `clipboard` set to `unnamedplus`?
* Do you have an applicable clipboard tool installed, from the ones listed in `:help clipboard`?
* More info about your environment could be helpful (X11 or wayland, compositor, WM/DE, ...)

**Comment by tagptroll1** [comment]
@MoSal Sorry for the late reply. I have tried having clipboard set to unnamedplus and unnamed.
I have both `xsel` and `xclip` installed (and $DISPLAY echos to `:1`) 
I'm on PopOS 24.04 With cosmic-de / wayland. 
inxi output for more details:
```
Graphics:
  Device-1: NVIDIA AD104 [GeForce RTX 4070 Ti] vendor: ASUSTeK driver: nvidia
    v: 555.58.02 arch: Lovelace pcie: speed: 5 GT/s lanes: 16 ports:
    active: none off: DP-4,DP-6 empty: DP-5,HDMI-A-2,HDMI-A-3 bus-ID: 01:00.0
    chip-ID: 10de:2782
  Device-2: AMD Raphael vendor: Micro-Star MSI driver: amdgpu v: kernel
    arch: RDNA-2 pcie: speed: 16 GT/s lanes: 16 ports: active: none empty: DP-1,
    DP-2, DP-3, HDMI-A-1, Writeback-1 bus-ID: 11:00.0 chip-ID: 1002:164e
    temp: 36.0 C
  Display: wayland server: X.org v: 1.21.1.11 with: Xwayland v: 24.1.0
    driver: gpu: nvidia,nvidia-nvswitch display-ID: 1
  Monitor-1: DP-4 model: 45WQHD240 res: 3440x1440 dpi: 82
    diag: 1165mm (45.9")
  Monitor-2: DP-6 model: Samsung C32HG7x res: 2560x1440 dpi: 93
    diag: 800mm (31.5")
  API: EGL v: 1.5 platforms: device: 0 drv: nvidia device: 2 drv: radeonsi
    device: 3 drv: swrast gbm: drv: nvidia surfaceless: drv: nvidia wayland:
    drv: nvidia x11: drv: zink inactive: device-1
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 555.58.02
    glx-v: 1.4 direct-render: yes renderer: NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2
```
